### ISSUE TITLE
Can't commit using pre-commit configuration (or whatever..)

### ISSUE THREAD

**Issue by yuvalabou** [py-libhdate/py-libhdate#72]
# Observed behavior
```
(hdate) dev@ubuntu-dev:~/py-libhdate/py-libhdate$ pip install --upgrade pip
Collecting pip
  Downloading pip-20.2.2-py2.py3-none-any.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 445 kB/s
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.2.2
(hdate) dev@ubuntu-dev:~/py-libhdate/py-libhdate$ git commit -a
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: Command: ('/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/bin/python3', '/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/bin/pip', 'install', '.')
Return code: 1
Expected return code: 0
Output:
    Processing /home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'

Errors:
      ERROR: Complete output from command /home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/bin/python3 /home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprc05e2a0:
      ERROR: Traceback (most recent call last):
        File "/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
          main()
        File "/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-kakdl1z4/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
          config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-kakdl1z4/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-kakdl1z4/overlay/lib/python3.5/site-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 6, in <module>
          assert sys.version_info >= (3, 6, 0), "black requires Python 3.6+"
      AssertionError: black requires Python 3.6+
      ----------------------------------------
    ERROR: Command "/home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/bin/python3 /home/dev/snap/pre-commit/common/.cache/pre-commit/repob6hpqgxg/py_env-python3/lib/python3.5/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprc05e2a0" failed with error code 1 in /tmp/pip-req-build-u8btpo4_
    WARNING: You are using pip version 19.1, however version 20.2.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
````
# Expected behavior
Allow me to commit the code

# Steps to reproduce
Try to commit

**Comment by tsvi** [comment]
Looks like black needs python 3.6+ to work correctly. What ubuntu version are you using?

**Comment by yuvalabou** [comment]
"Fixed" the pre-commit conf file as per the docs in both repos to be somewhat like this

```
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    exclude: 'setup.cfg'
  - id: end-of-file-fixer
    exclude: 'setup.cfg|CHANGELOG.rst'
  - id: check-added-large-files
  - id: detect-private-key
  - id: no-commit-to-branch
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3
```

And this is what the log says

```
(venv) dev@ubuntu-dev:~/py-libhdate$ git commit -m "Update .gitignore, also test for pre-commit error"
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
  GNU nano 4.8                                  /home/dev/snap/pre-commit/common/.cache/pre-commit/pre-commit.log
    returncode, cmd, retcode, output=(stdout, stderr),
pre_commit.util.CalledProcessError: Command: ('/home/dev/snap/pre-commit/common/.cache/pre-commit/repok84n2d4z/py_env-python3.5/bin/python3.5', '/home/dev/sn>Return code: 1
Expected return code: 0
Output:
    Processing /home/dev/snap/pre-commit/common/.cache/pre-commit/repok84n2d4z

Errors:
    ERROR: pre-commit-hooks requires Python '>=3.6.1' but the running Python is 3.5.2
    WARNING: You are using pip version 19.1, however version 20.2.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by tsvi** [comment]
Moving to poetry #83 should have fixed this issue as dependencies are more clear now.
