### ISSUE TITLE
Requirement is pinned for hdate 0.10.2: pytz>=2020.5,<2021.0

### ISSUE THREAD

**Issue by MartinHjelmare** [py-libhdate/py-libhdate#87]
# Observed behavior

- This library supports an integration in Home Assistant.
- The new pip resolver is more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- Requirement is pinned for hdate 0.10.2: pytz>=2020.5,<2021.0.

Thanks for your support of Home Assistant!

# Expected behavior

- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version. Or set a maximum version that is more forgiving.

# Steps to reproduce

```
(home-assistant) x:~/dev/home-assistant/core$ pip install -r requirements_all.txt
(home-assistant) x:~/dev/home-assistant/core$ pipdeptree -w silence -r -p pytz | grep hdate
...
 - hdate==0.10.2 [requires: pytz>=2020.5,<2021.0]
```

**Comment by tmostovi** [comment]
@MartinHjelmare, I have a hard time understanding how <2021.0 got added here.
According to `pyproject.toml` I only have a minimum version dependency, could you help me understand/debug what caused this requirement?

Below are the current dependencies.

```
[tool.poetry.dependencies]
        python = "~2.7 || ^3.6.1"
        pytz = "^2020.5"
        enum34 = { version = "^1.1.10", python = "~2.7" }
        astral = {version = "^2.2", python = "^3.6"}
```

**Comment by tsvi** [comment]
@MartinHjelmare, I have a hard time understanding how <2021.0 got added here.
According to `pyproject.toml` I only have a minimum version dependency, could you help me understand/debug what caused this requirement?

Below are the current dependencies.

```
[tool.poetry.dependencies]
    python = "~2.7 || ^3.6.1"
    pytz = "^2020.5"
    enum34 = { version = "^1.1.10", python = "~2.7" }
    astral = {version = "^2.2", python = "^3.6"}
```

**Comment by tsvi** [comment]
@MartinHjelmare Found it, would you mind updating the version in home-assistant/core?

**Comment by MartinHjelmare** [comment]
Sorry. I tried bumping but already with 0.10.2 I get this error:

```
2021-06-01 08:48:45 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up jewish_calendar platform for binary_sensor
Traceback (most recent call last):
  File "/home/martin/dev/home-assistant/core/homeassistant/helpers/entity_platform.py", line 222, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/home/martin/dev/home-assistant/core/homeassistant/helpers/entity_platform.py", line 347, in async_add_entities
    await asyncio.gather(*tasks)
  File "/home/martin/dev/home-assistant/core/homeassistant/helpers/entity_platform.py", line 539, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/home/martin/dev/home-assistant/core/homeassistant/helpers/entity.py", line 564, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/home/martin/dev/home-assistant/core/homeassistant/components/jewish_calendar/binary_sensor.py", line 80, in async_added_to_hass
    self._schedule_update()
  File "/home/martin/dev/home-assistant/core/homeassistant/components/jewish_calendar/binary_sensor.py", line 93, in _schedule_update
    update = zmanim.zmanim["sunrise"] + dt.timedelta(days=1)
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/hdate/zmanim.py", line 130, in zmanim
    for key, value in self.utc_zmanim.items()
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/hdate/zmanim.py", line 122, in utc_zmanim
    for key, value in self.get_utc_sun_time_full().items()
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/hdate/zmanim.py", line 313, in get_utc_sun_time_full
    first_light = self._get_utc_time_of_transit(106.1, True)
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/hdate/zmanim.py", line 295, in _get_utc_time_of_transit
    return self._datetime_to_minutes_offest(astral.sun.time_of_transit(
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/astral/sun.py", line 343, in time_of_transit
    hourangle = hour_angle(
  File "/home/martin/.virtualenvs/home-assistant/lib/python3.8/site-packages/astral/sun.py", line 243, in hour_angle
    HA = acos(h)
ValueError: math domain error
```

Looks like the bump of hdate to 0.10.2 from 0.9.12 in Home assistant broke it.

Since I can't verify that 0.10.3 works, I can't bump it. The problem needs a fix first.

**Comment by tsvi** [comment]
Ok, thanks. I'll investigate.
